//! Generate HTML samples for parse5 integration tests.
//!
//! This example outputs a JSON object containing various HTML samples
//! generated by ironhtml, which are then validated by parse5.

use ironhtml::{Element, Html, Node};

fn main() {
    let samples = Samples {
        simple_div: simple_div(),
        nested: nested(),
        with_attrs: with_attrs(),
        void_elements: void_elements(),
        escaped_text: escaped_text(),
        escaped_attrs: escaped_attrs(),
        full_document: full_document(),
        table: table(),
        list: list(),
        form: form(),
        semantic: semantic(),
        boolean_attrs: boolean_attrs(),
        deeply_nested: deeply_nested(),
    };

    // Output as JSON
    println!("{}", samples.to_json());
}

struct Samples {
    simple_div: String,
    nested: String,
    with_attrs: String,
    void_elements: String,
    escaped_text: String,
    escaped_attrs: String,
    full_document: String,
    table: String,
    list: String,
    form: String,
    semantic: String,
    boolean_attrs: String,
    deeply_nested: String,
}

impl Samples {
    fn to_json(&self) -> String {
        format!(
            r#"{{
  "simple_div": {},
  "nested": {},
  "with_attrs": {},
  "void_elements": {},
  "escaped_text": {},
  "escaped_attrs": {},
  "full_document": {},
  "table": {},
  "list": {},
  "form": {},
  "semantic": {},
  "boolean_attrs": {},
  "deeply_nested": {}
}}"#,
            json_string(&self.simple_div),
            json_string(&self.nested),
            json_string(&self.with_attrs),
            json_string(&self.void_elements),
            json_string(&self.escaped_text),
            json_string(&self.escaped_attrs),
            json_string(&self.full_document),
            json_string(&self.table),
            json_string(&self.list),
            json_string(&self.form),
            json_string(&self.semantic),
            json_string(&self.boolean_attrs),
            json_string(&self.deeply_nested),
        )
    }
}

fn json_string(s: &str) -> String {
    let escaped = s
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t");
    format!("\"{escaped}\"")
}

fn simple_div() -> String {
    Element::new("div").text("Hello").render()
}

fn nested() -> String {
    Element::new("div")
        .child("span", |e| e.text("Nested"))
        .render()
}

fn with_attrs() -> String {
    Element::new("div")
        .class("container")
        .attr("id", "main")
        .attr("data-value", "123")
        .render()
}

fn void_elements() -> String {
    Element::new("div")
        .node(Node::Element(Element::new("br")))
        .node(Node::Element(
            Element::new("img")
                .attr("src", "test.jpg")
                .attr("alt", "Test"),
        ))
        .node(Node::Element(Element::new("input").attr("type", "text")))
        .render()
}

fn escaped_text() -> String {
    Element::new("div")
        .text("<script>alert('xss')</script> & \"more\"")
        .render()
}

fn escaped_attrs() -> String {
    Element::new("div")
        .attr("data-value", "contains \"quotes\" & ampersand")
        .render()
}

fn full_document() -> String {
    Html::new()
        .raw("<!DOCTYPE html>")
        .elem("html", |e| {
            e.child("head", |e| e.child("title", |e| e.text("Test Page")))
                .child("body", |e| {
                    e.child("div", |e| {
                        e.class("content")
                            .child("h1", |e| e.text("Welcome"))
                            .child("p", |e| e.text("This is a test page."))
                    })
                })
        })
        .build()
}

fn table() -> String {
    Element::new("table")
        .child("thead", |e| {
            e.child("tr", |e| {
                e.child("th", |e| e.text("Name"))
                    .child("th", |e| e.text("Value"))
            })
        })
        .child("tbody", |e| {
            e.child("tr", |e| {
                e.child("td", |e| e.text("Item 1"))
                    .child("td", |e| e.text("100"))
            })
            .child("tr", |e| {
                e.child("td", |e| e.text("Item 2"))
                    .child("td", |e| e.text("200"))
            })
        })
        .render()
}

fn list() -> String {
    Element::new("ul")
        .child("li", |e| e.text("First"))
        .child("li", |e| e.text("Second"))
        .child("li", |e| e.text("Third"))
        .render()
}

fn form() -> String {
    Element::new("form")
        .attr("method", "post")
        .attr("action", "/submit")
        .child("div", |e| {
            e.child("label", |e| e.attr("for", "name").text("Name:"))
                .node(Node::Element(
                    Element::new("input")
                        .attr("type", "text")
                        .attr("id", "name")
                        .attr("name", "name"),
                ))
        })
        .child("div", |e| {
            e.child("label", |e| e.attr("for", "email").text("Email:"))
                .node(Node::Element(
                    Element::new("input")
                        .attr("type", "email")
                        .attr("id", "email")
                        .attr("name", "email"),
                ))
        })
        .child("button", |e| e.attr("type", "submit").text("Submit"))
        .render()
}

fn semantic() -> String {
    Element::new("div")
        .child("header", |e| e.child("nav", |e| e.text("Navigation")))
        .child("main", |e| {
            e.child("article", |e| {
                e.child("h1", |e| e.text("Article Title"))
                    .child("p", |e| e.text("Content"))
            })
        })
        .child("footer", |e| e.text("Footer content"))
        .render()
}

fn boolean_attrs() -> String {
    Element::new("div")
        .node(Node::Element(
            Element::new("input")
                .attr("type", "text")
                .bool_attr("disabled")
                .bool_attr("required"),
        ))
        .child("button", |e| e.bool_attr("disabled").text("Disabled"))
        .render()
}

fn deeply_nested() -> String {
    Element::new("div")
        .child("div", |e| {
            e.child("div", |e| {
                e.child("div", |e| {
                    e.child("div", |e| {
                        e.child("div", |e| e.child("span", |e| e.text("Deep")))
                    })
                })
            })
        })
        .render()
}
